import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const url='https://falloutmule.github.io/karambe-village-water-run/';
const response=await fetch(url,{cache:'no-store'});
assert.equal(response.status,200);
const live=Buffer.from(await response.arrayBuffer());
assert.ok(live.equals(fs.readFileSync('index.html')),'live Pages bytes match current root artifact');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const errors=[],unexpected=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('request',r=>{if(r.resourceType()!=='document'&&!r.url().startsWith('data:'))unexpected.push(r.url());});
page.on('requestfailed',r=>errors.push(r.failure()?.errorText));
try{
 await page.goto(url,{waitUntil:'networkidle'});
 assert.equal(await page.locator('.level-pick').count(),3);
 assert.equal(await page.locator('#levelSelectBox').isVisible(),true);
 assert.ok(await page.evaluate(()=>!CR.dev&&!CR.game&&CR.runFullSelfCheck().pass));
 await page.locator('#primaryBtn').click();
 await page.waitForTimeout(200);
 const right=await page.locator('[data-sfhs-control-id="right"]').boundingBox();
 const can=await page.locator('[data-sfhs-control-id="can"]').boundingBox();
 const cdp=await page.context().newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:right.x+right.width/2,y:right.y+right.height/2},{id:2,x:can.x+can.width/2,y:can.y+can.height/2}]});
 await page.waitForTimeout(350);
 assert.equal(await page.locator('[data-control-active="true"]').count(),2);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
 assert.equal(await page.locator('[data-control-active="true"]').count(),0);
 const check=await page.evaluate(()=>CR.runFullSelfCheck());
 assert.ok(check.pass);
 fs.mkdirSync('test-results/pages-live',{recursive:true});
 await page.screenshot({path:'test-results/pages-live/game.png'});
 await page.locator('#menuBtn').click();
 assert.equal(await page.locator('#primaryBtn').textContent(),'RESUME');
 await page.goto(url+'?dev=1',{waitUntil:'networkidle'});
 assert.ok(await page.evaluate(()=>!CR.dev&&!CR.game));
 assert.equal(await page.locator('.level-pick').count(),3);
 assert.equal(await page.locator('#levelSelectBox').isVisible(),true);
 assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);
 const proof={pass:true,url,status:response.status,bytes:live.length,sha256:crypto.createHash('sha256').update(live).digest('hex'),build:check.buildId,selfcheck:check,liveMultitouchAndCancel:true,publicDevFlagDisabled:true,errors,unexpectedRequests:unexpected,physicalPhone:'not tested'};
 fs.writeFileSync('test-results/pages-live/proof.json',JSON.stringify(proof,null,2));
 console.log(JSON.stringify(proof));
}finally{await browser.close();}
